presubmits:
- name: pull-test-inrepo-hello
  always_run: true
  decorate: false
  spec:
    containers:
      - image: alpine
        command:
          - /bin/sh
          - -c
          - echo hello there from repo
postsubmits:
- name: post-test-inrepo-hello
  decorate: false
  spec:
    containers:
      - image: alpine
        command:
          - /bin/sh
          - -c
          - echo hello from repo
