presubmits:
- name: pull-test-inrepo-hello
  always_run: true
  decorate: true
  branches:
  - my-branch
  spec:
    containers:
    - image: alpine
      command:
      - /bin/sh
      - -c
      - echo hello from repo
